spring.application.roleName=${APP_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-roleName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION}
api.security.token.issuer=${JWT_ISSUER}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_TOKEN}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.from=${EMAIL_SENDER}
spring.mail.roleName.sender=${EMAIL_ROLENAME}
spring.mail.url=${EMAIL_URL}




