INSERT INTO role (name) VALUES ('ADMIN')   ON CONFLICT (name) DO NOTHING;
INSERT INTO role (name) VALUES ('TRAINER') ON CONFLICT (name) DO NOTHING;
INSERT INTO role (name) VALUES ('USER')    ON CONFLICT (name) DO NOTHING;